<#
Ivory & Bloom Atelier - static site build script.

Assembles the deployable HTML files (repo root, journal/, and future page
directories) from src/pages/ + src/partials/. This is a BUILD-TIME-ONLY tool:
it has no runtime dependency, requires no npm install, and the site still
ships as plain static HTML/CSS/JS to Apache shared hosting exactly as before.

Do not hand-edit the generated files listed below - edit their src/pages/
source and re-run this script. Generated files carry a header comment
pointing back to their source.

Usage (from repo root, in PowerShell):
    powershell -File scripts/build.ps1
#>

$ErrorActionPreference = 'Stop'

$repoRoot    = Split-Path -Parent $PSScriptRoot
$pagesDir    = Join-Path $repoRoot 'src\pages'
$partialsDir = Join-Path $repoRoot 'src\partials'
$utf8NoBom   = New-Object System.Text.UTF8Encoding($false)

if (-not (Test-Path $pagesDir))    { throw "Missing $pagesDir" }
if (-not (Test-Path $partialsDir)) { throw "Missing $partialsDir" }

# Load all partials by filename (without extension).
$partials = @{}
Get-ChildItem -Path $partialsDir -Filter '*.html' | ForEach-Object {
    $name = [IO.Path]::GetFileNameWithoutExtension($_.Name)
    $partials[$name] = [System.IO.File]::ReadAllText($_.FullName, [System.Text.Encoding]::UTF8)
}

$includePattern = '<!--\s*INCLUDE:([a-zA-Z0-9\-]+)\s*-->'
$genHeader      = "<!-- AUTO-GENERATED by scripts/build.ps1 from src/pages/{0} - edit the source, not this file. -->`n"

$builtCount = 0
Get-ChildItem -Path $pagesDir -Filter '*.html' -Recurse | ForEach-Object {
    $page    = $_
    $relPath = $page.FullName.Substring($pagesDir.Length + 1)
    $outPath = Join-Path $repoRoot $relPath
    # {{ROOT}} resolves to './' at the site root (not '') so that links like
    # '{{ROOT}}#collections' become './#collections' - a same-page anchor on
    # index.html itself, and a link to the canonical '/' URL from any other
    # root-level page. Deeper pages get '../' per level.
    $depth   = ($relPath -split '\\').Length - 1
    $root    = if ($depth -eq 0) { './' } else { '../' * $depth }

    $content = [System.IO.File]::ReadAllText($page.FullName, [System.Text.Encoding]::UTF8)

    $evaluator = {
        param($m)
        $name = $m.Groups[1].Value
        if (-not $partials.ContainsKey($name)) {
            throw "Unknown partial '$name' referenced in $relPath"
        }
        return $partials[$name]
    }
    $content = [regex]::Replace($content, $includePattern, [System.Text.RegularExpressions.MatchEvaluator]$evaluator)
    $content = $content.Replace('{{ROOT}}', $root)

    $relPathForward = $relPath -replace '\\', '/'
    $content = ($genHeader -f $relPathForward) + $content

    $outDir = Split-Path -Parent $outPath
    if ($outDir -and -not (Test-Path $outDir)) {
        New-Item -ItemType Directory -Path $outDir -Force | Out-Null
    }
    [System.IO.File]::WriteAllText($outPath, $content, $utf8NoBom)
    Write-Host "Built $relPathForward"
    $builtCount++
}

Write-Host "`nDone - $builtCount page(s) built from src/pages/."